name: Setup MariaDB
inputs:
  mariadb-version:
    description: The MariaDB version to download (if necessary) and use
  database:
    description: Database to create(optional - defaults to test)
  username:
    description: Database user to create(optional - defaults to test)
  password:
    description: Database user password to create(optional - defaults to password)
  root-password:
    description: Default root password for mariadb (optional - defaults to password)
runs:
  using: node14
  main: index.js
